branch-defaults:
  default:
    environment: wordcloud-env
    group_suffix: null
global:
  application_name: wordcloud
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
